name: leobookapp
description: "LeoBook: Elite Autonomous Betting Dashboard by Materialless LLC."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  http: ^1.6.0
  csv: ^6.0.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  url_launcher: ^6.3.2
  shimmer: ^3.0.0
  google_fonts: ^4.0.0
  shared_preferences: ^2.5.2
  supabase_flutter: ^2.3.0
  flutter_dotenv: ^5.2.1
  provider: ^6.1.2
  google_sign_in: 6.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  # Ensure the .env file exists in your project directory or update the path accordingly
  assets:
    - .env # Verify that this file exists; create it if needed to fix the error.